"use client"

import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react"
import { LANGUAGES, translations, type LangCode, type TKey } from "@/lib/i18n"

export type Reminder = { id:string; icon:string; label:string; time:string; done:boolean; repeat:"daily"|"once"; lastCompleted?:string; medication?:boolean; completedAt?:number }
export type PageId = "dashboard"|"games"|"memory"|"reminders"|"memory-book"|"journal"|"language"|"caregiver"|"profile"
export type Mood = { emoji:string; label:string }
export type FamilyMember = { id:string; name:string; relationship:string; image:string; note?:string }
export type Activity = { id:string; type:string; title:string; detail:string; timestamp:number; value?:number }
export type Journal = { id:string; text:string; transcript?:string; createdAt:number; audioDataUrl?:string }
export type ProfileData = { name:string; age:string; lang:LangCode; mood:Mood; textScale:number; selectedVoiceName?:string|null; contrast:boolean; emergencyMode:boolean; caregiverName:string; caregiverPhone:string; caregiverCode:string; familyMembers:FamilyMember[]; activities:Activity[]; journals:Journal[]; badges:string[]; moodHistory:{mood:Mood;timestamp:number}[] }

const MOODS: Mood[] = [{emoji:"😀",label:"Great"},{emoji:"😊",label:"Good"},{emoji:"😐",label:"Okay"},{emoji:"😔",label:"Low"}]
const INITIAL_REMINDERS: Reminder[] = [
 {id:"r1",icon:"💊",label:"Blood pressure medicine",time:"6:00 PM",done:false,repeat:"daily",medication:true},
 {id:"r2",icon:"💧",label:"Drink water",time:"6:30 PM",done:false,repeat:"daily"},
 {id:"r3",icon:"🚶",label:"Evening walk",time:"7:00 PM",done:false,repeat:"daily"},
 {id:"r4",icon:"👨‍⚕️",label:"Doctor appointment",time:"10:30 AM",done:false,repeat:"once"},
]
const AUTH_KEY="smriti-users", SESSION_KEY="smriti-session", LEGACY_KEY="smriti-profile"
type AuthUser={username:string;passwordHash:string;displayName:string}
function simpleHash(str:string){let h=0;for(let i=0;i<str.length;i++){h=((h<<5)-h)+str.charCodeAt(i);h|=0}return h.toString(36)}
function profileKey(username:string){return `smriti-profile:${username.trim().toLowerCase()}`}
function remindersKey(username:string){return `${profileKey(username)}:reminders`}
function statsKey(username:string){return `${profileKey(username)}:stats`}
function emptyProfile():ProfileData{return {name:"",age:"",lang:"en",mood:MOODS[1],textScale:1,selectedVoiceName:null,contrast:false,emergencyMode:false,caregiverName:"",caregiverPhone:"",caregiverCode:"",familyMembers:[],activities:[],journals:[],badges:[],moodHistory:[]}}
function dateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function normalizeProfile(p:any):ProfileData{const e=emptyProfile();return {...e,...p,familyMembers:Array.isArray(p?.familyMembers)?p.familyMembers:[],activities:Array.isArray(p?.activities)?p.activities:[],journals:Array.isArray(p?.journals)?p.journals:[],badges:Array.isArray(p?.badges)?p.badges:[],moodHistory:Array.isArray(p?.moodHistory)?p.moodHistory:[]}}
function readJson<T>(key:string,fallback:T):T{try{const r=localStorage.getItem(key);return r?JSON.parse(r):fallback}catch{return fallback}}
function writeJson(key:string,value:any){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}

export type AppContextType={
 lang:LangCode;setLang:(c:LangCode)=>void;t:(k:TKey)=>string;languages:typeof LANGUAGES;page:PageId;navigate:(p:PageId)=>void;
 speak:(s:string)=>void;speakKey:(k:TKey)=>void;textScale:number;setTextScale:(v:number)=>void;userName:string;userAge:string;onboardingDone:boolean;saveProfile:(n:string,a:string,l:LangCode,m:Mood)=>void;
 reminders:Reminder[];toggleReminder:(id:string)=>void;deleteReminder:(id:string)=>void;addReminder:(l:string,t:string,i:string,repeat?:"daily"|"once",medication?:boolean)=>void;
 mood:Mood;cycleMood:()=>void;moods:Mood[];setMood:(m:Mood)=>void;toast:(m:string)=>void;toastMsg:string|null;score:number;addPoints:(n:number)=>void;gamesCompleted:number;completeGame:(accuracy?:number)=>void;
 activities:Activity[];familyMembers:FamilyMember[];addFamilyMember:(m:Omit<FamilyMember,"id">)=>void;removeFamilyMember:(id:string)=>void;journals:Journal[];addJournal:(j:Omit<Journal,"id"|"createdAt">)=>void;deleteJournal:(id:string)=>void;badges:string[];
 contrast:boolean;setContrast:(v:boolean)=>void;emergencyMode:boolean;setEmergencyMode:(v:boolean)=>void;caregiverName:string;caregiverPhone:string;setCaregiver:(n:string,p:string)=>void;caregiverCode:string;generateCaregiverCode:()=>string;confirmReminderWithPhoto:(id:string)=>void;
 isLoggedIn:boolean;login:(u:string,p:string)=>boolean;signup:(u:string,p:string,d:string)=>boolean;logout:()=>void;authError:string|null;setAuthError:(e:string|null)=>void;
 selectedVoiceName:string|null;setSelectedVoiceName:(n:string|null)=>void;availableVoices:SpeechSynthesisVoice[]
}
const AppContext=createContext<AppContextType|null>(null)
export function useApp(){const c=useContext(AppContext);if(!c)throw new Error("useApp must be used within AppProvider");return c}

export function AppProvider({children}:{children:ReactNode}){
 const [lang,setLangState]=useState<LangCode>("en"),[page,setPage]=useState<PageId>("dashboard"),[reminders,setReminders]=useState<Reminder[]>(INITIAL_REMINDERS),[mood,setMoodState]=useState(MOODS[1]),[toastMsg,setToastMsg]=useState<string|null>(null),[score,setScore]=useState(78),[gamesCompleted,setGamesCompleted]=useState(0),[textScale,setTextScaleState]=useState(1),[userName,setUserName]=useState(""),[userAge,setUserAge]=useState(""),[onboardingDone,setOnboardingDone]=useState(false),[activities,setActivities]=useState<Activity[]>([]),[familyMembers,setFamilyMembers]=useState<FamilyMember[]>([]),[journals,setJournals]=useState<Journal[]>([]),[badges,setBadges]=useState<string[]>([]),[contrast,setContrastState]=useState(false),[emergencyMode,setEmergencyModeState]=useState(false),[caregiverName,setCaregiverName]=useState(""),[caregiverPhone,setCaregiverPhone]=useState(""),[caregiverCode,setCaregiverCode]=useState(""),[isLoggedIn,setIsLoggedIn]=useState(false),[authError,setAuthError]=useState<string|null>(null),[selectedVoiceName,setSelectedVoiceNameState]=useState<string|null>(null),[availableVoices,setAvailableVoices]=useState<SpeechSynthesisVoice[]>([])
 const currentUser=useRef(""), fired=useRef<Record<string,string>>({}),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null),lastDay=useRef("")
 const persist=useCallback((patch:Partial<ProfileData>)=>{if(!currentUser.current)return;const key=profileKey(currentUser.current);const p=normalizeProfile(readJson(key,{}));writeJson(key,{...p,...patch})},[])
 const logActivity=useCallback((type:string,title:string,detail:string,value?:number)=>{const a:Activity={id:`a${Date.now()}-${Math.random().toString(36).slice(2,6)}`,type,title,detail,timestamp:Date.now(),value};setActivities(prev=>{const next=[a,...prev].slice(0,100);persist({activities:next});return next})},[persist])
 const loadProfile=useCallback((username:string)=>{currentUser.current=username;const p=normalizeProfile(readJson(profileKey(username),{}));setUserName(p.name);setUserAge(p.age);setLangState(p.lang);setMoodState(p.mood);setTextScaleState(p.textScale||1);setSelectedVoiceNameState(p.selectedVoiceName??null);setContrastState(!!p.contrast);setEmergencyModeState(!!p.emergencyMode);setCaregiverName(p.caregiverName||"");setCaregiverPhone(p.caregiverPhone||"");setCaregiverCode(p.caregiverCode||"");setFamilyMembers(p.familyMembers);setActivities(p.activities);setJournals(p.journals);setBadges(p.badges);setOnboardingDone(!!p.name);const rs=readJson<Reminder[]|null>(remindersKey(username),null);setReminders(rs&&Array.isArray(rs)?rs:INITIAL_REMINDERS.map(r=>({...r})));const stats=readJson<{score?:number;gamesCompleted?:number}|null>(statsKey(username),null);setScore(stats?.score??78);setGamesCompleted(stats?.gamesCompleted??0);fired.current={}},[])
 useEffect(()=>{const s=readJson<any>(SESSION_KEY,null);if(s?.loggedIn&&s.username){setIsLoggedIn(true);loadProfile(s.username)}else{const legacy=readJson<any>(LEGACY_KEY,null);if(legacy?.name){/* legacy data remains untouched; users can sign up/login */}}},[loadProfile])
 useEffect(()=>{if(!currentUser.current)return;writeJson(remindersKey(currentUser.current),reminders);writeJson(statsKey(currentUser.current),{score,gamesCompleted})},[reminders,score,gamesCompleted])
 useEffect(()=>{if(typeof window==="undefined"||!("speechSynthesis"in window))return;const load=()=>setAvailableVoices(window.speechSynthesis.getVoices());load();window.speechSynthesis.onvoiceschanged=load;return()=>{window.speechSynthesis.onvoiceschanged=null}},[])
 const toast=useCallback((m:string)=>{setToastMsg(m);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToastMsg(null),2600)},[])
 const speak=useCallback((text:string)=>{if(typeof window!=="undefined"&&"speechSynthesis"in window){window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const sl=LANGUAGES.find(l=>l.code===lang)?.speechLang??"en-IN";u.lang=sl;u.rate=.8;u.pitch=1;u.volume=1;const vs=window.speechSynthesis.getVoices();u.voice=(selectedVoiceName&&vs.find(v=>v.name===selectedVoiceName))||vs.find(v=>v.lang.toLowerCase()===sl.toLowerCase())||vs.find(v=>v.lang.toLowerCase().startsWith(sl.split("-")[0]))||vs.find(v=>v.lang.toLowerCase().includes("-in"))||vs[0];window.speechSynthesis.speak(u)}else toast(text)},[lang,selectedVoiceName,toast])
 const speakKey=useCallback((k:TKey)=>speak(translations[lang][k]),[lang,speak])
 const login=useCallback((u:string,p:string)=>{try{const users=readJson<AuthUser[]>(AUTH_KEY,[]);const user=users.find(x=>x.username.toLowerCase()===u.trim().toLowerCase());if(!user){setAuthError("User not found. Please sign up first.");return false}if(user.passwordHash!==simpleHash(p)){setAuthError("Incorrect password.");return false}localStorage.setItem(SESSION_KEY,JSON.stringify({loggedIn:true,username:user.username}));setIsLoggedIn(true);setAuthError(null);loadProfile(user.username);return true}catch{setAuthError("Something went wrong. Try again.");return false}},[loadProfile])
 const signup=useCallback((u:string,p:string,d:string)=>{if(!u.trim()||!p.trim()||!d.trim()){setAuthError("All fields are required.");return false}if(p.length<4){setAuthError("Password must be at least 4 characters.");return false}try{const users=readJson<AuthUser[]>(AUTH_KEY,[]);if(users.some(x=>x.username.toLowerCase()===u.trim().toLowerCase())){setAuthError("Username already taken. Try another.");return false}const username=u.trim();users.push({username,passwordHash:simpleHash(p),displayName:d.trim()});writeJson(AUTH_KEY,users);writeJson(profileKey(username),{...emptyProfile(),name:d.trim()});localStorage.setItem(SESSION_KEY,JSON.stringify({loggedIn:true,username}));setIsLoggedIn(true);setAuthError(null);loadProfile(username);return true}catch{setAuthError("Something went wrong. Try again.");return false}},[loadProfile])
 const logout=useCallback(()=>{localStorage.removeItem(SESSION_KEY);setIsLoggedIn(false);setPage("dashboard");setOnboardingDone(false);setUserName("");setUserAge("");setReminders(INITIAL_REMINDERS.map(r=>({...r})));setActivities([]);setFamilyMembers([]);setJournals([]);setBadges([]);setCaregiverName("");setCaregiverPhone("");setCaregiverCode("");setScore(78);setGamesCompleted(0);currentUser.current="";if(typeof window!=="undefined"&&"speechSynthesis"in window)window.speechSynthesis.cancel()},[])
 const saveProfile=useCallback((n:string,a:string,l:LangCode,m:Mood)=>{const now=Date.now();setUserName(n.trim());setUserAge(a);setLangState(l);setMoodState(m);setOnboardingDone(true);const hist=[{mood:m,timestamp:now}];persist({name:n.trim(),age:a,lang:l,mood:m,textScale,moodHistory:hist});logActivity("mood","Mood check-in",`${m.emoji} ${m.label}`)},[logActivity,persist,textScale])
 const setTextScale=useCallback((v:number)=>{const n=Math.max(1,Math.min(1.8,Math.round(v*10)/10));setTextScaleState(n);persist({textScale:n})},[persist])
 const setLang=useCallback((c:LangCode)=>{setLangState(c);persist({lang:c});toast(`${translations[c].languageChanged} ${translations[c].langName}`);setTimeout(()=>speak(translations[c].v_welcome),50)},[persist,speak,toast])
 const navigate=useCallback((p:PageId)=>{setPage(p);if(typeof window!=="undefined")window.scrollTo(0,0)},[])
 const toggleReminder=useCallback((id:string)=>setReminders(prev=>prev.map(r=>{if(r.id!==id)return r;const done=!r.done;const next={...r,done,lastCompleted:done?dateKey():r.lastCompleted,completedAt:done?Date.now():r.completedAt};if(done)logActivity("reminder","Reminder completed",`${r.icon} ${r.label}`);return next})),[logActivity])
 const deleteReminder=useCallback((id:string)=>{const r=reminders.find(x=>x.id===id);setReminders(prev=>prev.filter(x=>x.id!==id));if(r)logActivity("reminder","Reminder deleted",r.label)},[logActivity,reminders])
 const addReminder=useCallback((label:string,time:string,icon:string,repeat:"daily"|"once"="daily",medication=false)=>{const r={id:`r${Date.now()}-${Math.random().toString(36).slice(2,5)}`,icon:icon||"⏰",label,time:time||"Anytime",done:false,repeat,medication};setReminders(prev=>[...prev,r]);logActivity("reminder","Reminder added",`${icon} ${label} · ${time||"Anytime"}`)},[logActivity])
 const setMood=useCallback((m:Mood)=>{setMoodState(m);persist({mood:m});const now=Date.now();const p=normalizeProfile(readJson(profileKey(currentUser.current),{}));persist({moodHistory:[...(p.moodHistory||[]),{mood:m,timestamp:now}].slice(-100)});logActivity("mood","Mood check-in",`${m.emoji} ${m.label}`)},[logActivity,persist])
 const cycleMood=useCallback(()=>{const i=MOODS.findIndex(x=>x.label===mood.label);setMood(MOODS[(i+1)%MOODS.length])},[mood,setMood])
 const addPoints=useCallback((n:number)=>setScore(s=>Math.min(100,s+Math.max(0,n))),[])
 const completeGame=useCallback((accuracy=0)=>{setGamesCompleted(g=>g+1);setScore(s=>Math.min(100,s+Math.max(1,Math.round(accuracy/20))));logActivity("game","Cognitive game completed",`${accuracy}% accuracy`,accuracy);setBadges(prev=>{const next=[...prev];if(accuracy>=80&&!next.includes("Sharp Mind"))next.push("Sharp Mind");persist({badges:next});return next})},[logActivity,persist])
 const addFamilyMember=useCallback((m:Omit<FamilyMember,"id">)=>setFamilyMembers(prev=>{const n=[...prev,{...m,id:`f${Date.now()}-${Math.random().toString(36).slice(2,5)}`}];persist({familyMembers:n});logActivity("family","Family member added",`${m.name} · ${m.relationship}`);return n}),[logActivity,persist])
 const removeFamilyMember=useCallback((id:string)=>setFamilyMembers(prev=>{const m=prev.find(x=>x.id===id);const n=prev.filter(x=>x.id!==id);persist({familyMembers:n});if(m)logActivity("family","Family member removed",m.name);return n}),[logActivity,persist])
 const addJournal=useCallback((j:Omit<Journal,"id"|"createdAt">)=>setJournals(prev=>{const n=[{...j,id:`j${Date.now()}-${Math.random().toString(36).slice(2,5)}`,createdAt:Date.now()},...prev];persist({journals:n});logActivity("journal","Journal saved",j.text?.slice(0,80)||"Voice journal entry");return n}),[logActivity,persist])
 const deleteJournal=useCallback((id:string)=>setJournals(prev=>{const n=prev.filter(x=>x.id!==id);persist({journals:n});return n}),[persist])
 const setContrast=useCallback((v:boolean)=>{setContrastState(v);persist({contrast:v})},[persist]);const setEmergencyMode=useCallback((v:boolean)=>{setEmergencyModeState(v);persist({emergencyMode:v})},[persist]);const setCaregiver=useCallback((n:string,p:string)=>{setCaregiverName(n.trim());setCaregiverPhone(p.trim());persist({caregiverName:n.trim(),caregiverPhone:p.trim()});logActivity("caregiver","Caregiver contact saved",`${n.trim()}${p.trim()?` · ${p.trim()}`:""}`)},[logActivity,persist])
 const generateCaregiverCode=useCallback(()=>{const c=Math.random().toString(36).slice(2,8).toUpperCase();setCaregiverCode(c);persist({caregiverCode:c});toast(`Caregiver link code: ${c}`);return c},[persist,toast])
 const confirmReminderWithPhoto=useCallback((id:string)=>{const r=reminders.find(x=>x.id===id);setReminders(prev=>prev.map(x=>x.id===id?{...x,done:true,lastCompleted:dateKey(),completedAt:Date.now()}:x));if(r)logActivity("reminder","Medication confirmed with photo",r.label);toast("Medication confirmation saved")},[logActivity,reminders,toast])
 useEffect(()=>{if(!onboardingDone)return;const check=()=>{const now=new Date();const today=dateKey(now);if(lastDay.current!==today){lastDay.current=today;setReminders(prev=>prev.map(r=>r.repeat==="daily"?{...r,done:false,lastCompleted:undefined,completedAt:undefined}:r))}const minute=now.getHours()*60+now.getMinutes();for(const r of reminders){if(r.done||r.time==="Anytime")continue;const m=r.time.trim().match(/^(\d{1,2}):(\d{2})\s*(AM|PM)?$/i);if(!m)continue;let h=Number(m[1]),mi=Number(m[2]);const ap=m[3]?.toUpperCase();if(ap==="PM"&&h<12)h+=12;if(ap==="AM"&&h===12)h=0;const target=h*60+mi;const diff=minute-target;const fireKey=`${today}-${r.id}`;if(diff>=0&&diff<=1&&!fired.current[fireKey]){fired.current[fireKey]=fireKey;setActiveReminderState(r)}}};check();const id=window.setInterval(check,15000);return()=>window.clearInterval(id)},[onboardingDone,reminders])
 const [activeReminder,setActiveReminderState]=useState<Reminder|null>(null)
 useEffect(()=>{if(!activeReminder)return;const id=window.setTimeout(()=>speak(`Reminder: ${activeReminder.label}. It is time now.`),250);return()=>window.clearTimeout(id)},[activeReminder,speak])
 const value=useMemo<AppContextType>(()=>({lang,setLang,t:(k)=>translations[lang][k],languages:LANGUAGES,page,navigate,speak,speakKey,textScale,setTextScale,userName,userAge,onboardingDone,saveProfile,reminders,toggleReminder,deleteReminder,addReminder,mood,cycleMood,moods:MOODS,setMood,toast,toastMsg,score,addPoints,gamesCompleted,completeGame,activities,familyMembers,addFamilyMember,removeFamilyMember,journals,addJournal,deleteJournal,badges,contrast,setContrast,emergencyMode,setEmergencyMode,caregiverName,caregiverPhone,setCaregiver,caregiverCode,generateCaregiverCode,confirmReminderWithPhoto,isLoggedIn,login,signup,logout,authError,setAuthError,selectedVoiceName,setSelectedVoiceName:(n)=>{setSelectedVoiceNameState(n);persist({selectedVoiceName:n})},availableVoices}),[lang,setLang,navigate,speak,speakKey,textScale,setTextScale,userName,userAge,onboardingDone,saveProfile,reminders,toggleReminder,deleteReminder,addReminder,mood,cycleMood,setMood,toast,toastMsg,score,addPoints,gamesCompleted,completeGame,activities,familyMembers,addFamilyMember,removeFamilyMember,journals,addJournal,deleteJournal,badges,contrast,setContrast,emergencyMode,setEmergencyMode,caregiverName,caregiverPhone,setCaregiver,caregiverCode,generateCaregiverCode,confirmReminderWithPhoto,isLoggedIn,login,signup,logout,authError,selectedVoiceName,availableVoices,persist])
 return <AppContext.Provider value={value}><div className={`${contrast?"contrast-mode":""} ${emergencyMode?"emergency-mode":""}`} style={{fontSize:`${textScale}em`}}>{children}</div>{activeReminder&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/50 p-4"><div className="w-full max-w-md rounded-3xl border bg-card p-7 text-center shadow-2xl"><div className="mx-auto grid size-20 place-items-center rounded-full bg-primary/10 text-4xl">{activeReminder.icon}</div><p className="mt-4 font-bold text-primary">⏰ Reminder</p><h2 className="mt-2 text-2xl font-extrabold">{activeReminder.label}</h2><p className="mt-2 text-muted-foreground">{activeReminder.time}</p>{activeReminder.medication&&<p className="mt-2 text-sm font-semibold text-primary">Medication reminder · photo confirmation available</p>}<button onClick={()=>speak(`${activeReminder.label}. It is time now.`)} className="mt-5 w-full rounded-2xl border p-3 font-bold">🔊 Read Again</button><button onClick={()=>{toggleReminder(activeReminder.id);setActiveReminderState(null)}} className="mt-2 w-full rounded-2xl bg-primary p-4 font-extrabold text-primary-foreground">✓ Mark as Done</button><button onClick={()=>setActiveReminderState(null)} className="mt-2 w-full rounded-2xl border p-3 font-bold">Dismiss</button></div></div>}</AppContext.Provider>
}
