"use client"
import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import { ArrowLeft, CheckCircle2, RotateCcw, Trophy, Volume2 } from "lucide-react"
import { useApp } from "@/components/app-provider"
import { Panel } from "@/components/ui-bits"
import type { TKey } from "@/lib/i18n"

export type GameType = "memory" | "focus" | "pattern"
const ITEMS=["🍎","🍌","🌸","🏠","🕊️","☕","🌳","📻","🔑","🧸","☂️","🕯️"]
type Round={prompt:string[];answer:string;choices:string[]}
type Phase="memorize"|"choose"|"feedback"|"complete"
function shuffle<T>(a:T[]){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function sample<T>(a:T[],n:number){return shuffle(a).slice(0,n)}
function buildRound(type:GameType,difficulty:number):Round{
 const answer=sample(ITEMS,1)[0]
 if(type==="memory")return {prompt:[answer],answer,choices:shuffle([answer,...sample(ITEMS.filter(x=>x!==answer),difficulty+2)])}
 if(type==="focus")return {prompt:[answer],answer,choices:shuffle([answer,...sample(ITEMS.filter(x=>x!==answer),difficulty+4)])}
 const [a,b]=sample(ITEMS,2);const patterns=[{seq:[a,b,a,b],next:a},{seq:[a,a,b,a,a],next:b},{seq:[a,b,b,a,b],next:b}];const p=patterns[Math.floor(Math.random()*patterns.length)];return {prompt:p.seq,answer:p.next,choices:shuffle([p.next,...sample(ITEMS.filter(x=>x!==p.next),difficulty+2)])}
}
const META:Record<GameType,{titleKey:TKey;instrKey:TKey;icon:string}>={memory:{titleKey:"g_memory_name",instrKey:"memoryInstruction",icon:"🧠"},focus:{titleKey:"g_focus_name",instrKey:"focusInstruction",icon:"🔎"},pattern:{titleKey:"g_pattern_name",instrKey:"patternInstruction",icon:"🧩"}}
export function GamePlay({type,onExit}:{type:GameType;onExit:()=>void}){
 const {t,speak,addPoints,completeGame,toast,score}=useApp();const meta=META[type];const total=score>=85?6:score<55?4:5;const difficulty=score>=85?3:score>=70?2:1
 const [round,setRound]=useState(1),[correct,setCorrect]=useState(0),[streak,setStreak]=useState(0),[phase,setPhase]=useState<Phase>(type==="memory"?"memorize":"choose"),[current,setCurrent]=useState(()=>buildRound(type,difficulty)),[picked,setPicked]=useState<string|null>(null);const timers=useRef<ReturnType<typeof setTimeout>[]>([])
 useEffect(()=>()=>timers.current.forEach(clearTimeout),[])
 useEffect(()=>{if(type!=="memory"||phase!=="memorize")return;const id=setTimeout(()=>setPhase("choose"),2200);return()=>clearTimeout(id)},[type,phase])
 const next=useCallback(()=>{setPicked(null);setCurrent(buildRound(type,difficulty));setPhase(type==="memory"?"memorize":"choose")},[type,difficulty])
 const answer=useCallback((choice:string)=>{if(phase!=="choose")return;const right=choice===current.answer;setPicked(choice);setPhase("feedback");if(right){setCorrect(c=>c+1);setStreak(s=>s+1);addPoints(2);toast(`${t("correct")} 👏`);speak(t("v_correct"))}else{setStreak(0);toast(t("tryAgain"))}const id=setTimeout(()=>{const newCorrect=correct+(right?1:0);if(round>=total){setPhase("complete");completeGame(Math.round(newCorrect/total*100))}else{setRound(r=>r+1);next()}},900);timers.current.push(id)},[phase,current.answer,addPoints,toast,t,speak,correct,round,total,completeGame,next])
 const accuracy=useMemo(()=>Math.round(correct/total*100),[correct,total])
 const restart=useCallback(()=>{timers.current.forEach(clearTimeout);timers.current=[];setRound(1);setCorrect(0);setStreak(0);setPicked(null);setCurrent(buildRound(type,difficulty));setPhase(type==="memory"?"memorize":"choose")},[type,difficulty])
 if(phase==="complete")return <Panel className="mx-auto max-w-xl text-center"><div className="mx-auto mb-4 grid size-16 place-items-center rounded-full bg-accent/12 text-accent"><Trophy className="size-8"/></div><h2 className="text-2xl font-extrabold">{t("sessionComplete")}</h2><p className="mt-2 text-muted-foreground">{t("score")}: {correct}/{total}</p><div className="my-6"><div className="text-5xl font-extrabold text-primary">{accuracy}%</div><div className="text-sm font-bold uppercase tracking-wide text-muted-foreground">{t("accuracy")}</div></div><div className="flex justify-center gap-3"><button onClick={restart} className="inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 font-extrabold text-primary-foreground"><RotateCcw className="size-4"/> {t("playAgain")}</button><button onClick={onExit} className="inline-flex items-center gap-2 rounded-xl border px-5 py-3 font-bold"><ArrowLeft className="size-4"/> {t("backToGames")}</button></div></Panel>
 const showTarget=type!=="memory"||phase==="memorize"
 return <Panel className="mx-auto max-w-2xl"><div className="mb-4 flex items-center justify-between"><button onClick={onExit} className="inline-flex items-center gap-1.5 text-sm font-semibold text-muted-foreground"><ArrowLeft className="size-4"/> {t("backToGames")}</button><button onClick={()=>speak(t(meta.instrKey))} className="inline-flex items-center gap-1.5 rounded-lg bg-muted px-3 py-1.5 text-sm font-semibold"><Volume2 className="size-4"/> {t("readInstructions")}</button></div><div className="text-center"><h2 className="text-2xl font-extrabold">{meta.icon} {t(meta.titleKey)}</h2><p className="mt-1 text-muted-foreground">{t(meta.instrKey)}</p></div><div className="my-6 grid min-h-56 place-items-center rounded-3xl border-2 border-dashed border-primary/30 bg-gradient-to-br from-primary/5 to-card p-6">{type==="pattern"?<div className="flex flex-wrap items-center justify-center gap-3">{current.prompt.map((p,i)=><span key={i} className="text-5xl">{p}</span>)}<span className="grid size-16 place-items-center rounded-2xl border-2 border-dashed text-3xl font-bold text-primary">?</span></div>:showTarget?<div className="text-center">{type==="focus"&&<p className="mb-2 text-sm font-bold uppercase text-muted-foreground">Target</p>}<span className="text-7xl">{current.prompt[0]}</span>{type==="memory"&&<p className="mt-3 animate-pulse text-sm font-bold text-primary">{t("memorize")}</p>}</div>:<span className="text-6xl text-primary/40">❓</span>}</div><div className={`grid gap-3 ${type==="focus"?"grid-cols-3":"grid-cols-2"}`}>{current.choices.map((c,i)=>{const isAnswer=c===current.answer,isPicked=picked===c;let cls="border-border bg-card hover:border-primary";if(phase==="feedback")cls=isAnswer?"border-accent bg-accent/12 text-accent":isPicked?"border-destructive bg-destructive/10 text-destructive":"border-border bg-card opacity-50";return <button key={`${c}-${i}`} disabled={phase!=="choose"} onClick={()=>answer(c)} className={`flex items-center justify-center gap-2 rounded-2xl border-2 p-4 text-lg font-extrabold ${cls}`}><span className="text-2xl">{c}</span>{phase==="feedback"&&isAnswer&&<CheckCircle2 className="size-5"/>}</button>})}</div><div className="mt-6 flex justify-center gap-6 text-sm font-bold"><span>{t("round")} {round}/{total}</span><span className="text-primary">{t("score")} {correct}</span><span className="text-accent">{t("streakLabel")} {streak} {streak>0?"🔥":""}</span></div><p className="mt-2 text-center text-xs text-muted-foreground">Adaptive level: {difficulty}</p></Panel>
}
