"use client"
import { useRef,useState } from "react"
import { Mic, Square, Trash2, Play, Square as StopIcon } from "lucide-react"
import { Panel } from "@/components/ui-bits"
import { useApp } from "@/components/app-provider"
export function Journal(){const {journals,addJournal,deleteJournal,speak,toast}=useApp();const [text,setText]=useState(""),[recording,setRecording]=useState(false),[elapsed,setElapsed]=useState(0);const rec=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),timer=useRef<ReturnType<typeof setInterval>|null>(null)
 function saveText(){if(!text.trim())return;addJournal({text:text.trim()});setText("");toast("Journal note saved ✓")}
 async function start(){try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error("unsupported");const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{const blob=new Blob(chunks.current,{type:r.mimeType||"audio/webm"});const reader=new FileReader();reader.onload=()=>{addJournal({text:text.trim(),audioDataUrl:String(reader.result)});setText("");toast("Voice journal saved ✓")};reader.readAsDataURL(blob);stream.getTracks().forEach(x=>x.stop());if(timer.current)clearInterval(timer.current);setElapsed(0);setRecording(false)};r.start();rec.current=r;setRecording(true);setElapsed(0);timer.current=setInterval(()=>setElapsed(x=>x+1),1000)}catch{toast("Microphone is unavailable. You can still save a typed note.")}}
 function stop(){rec.current?.stop()}
 return <div className="space-y-5"><header><h1 className="text-3xl font-extrabold">Voice Journal 🎙️</h1><p className="mt-1 text-muted-foreground">Speak or write a daily memory, feeling or story. Entries are saved to this user profile.</p></header><Panel><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="How was your day?" className="min-h-32 w-full rounded-2xl border p-4"/><div className="mt-3 flex flex-wrap gap-2"><button onClick={recording?stop:start} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-3 font-bold text-primary-foreground">{recording?<><Square className="size-4"/>Stop ({elapsed}s)</>:<><Mic className="size-4"/>Record voice</>}</button><button onClick={saveText} disabled={!text.trim()} className="rounded-xl border px-4 py-3 font-bold disabled:opacity-50">Save note</button></div><p className="mt-3 text-xs text-muted-foreground">Voice recordings are stored locally as audio data. Keep recordings short to avoid browser storage limits.</p></Panel><Panel><h2 className="text-lg font-bold">Recent journal</h2><div className="mt-3 space-y-3">{journals.length?journals.map(j=><article key={j.id} className="rounded-2xl bg-muted/50 p-4"><div className="flex items-start justify-between gap-3"><small className="text-muted-foreground">{new Date(j.createdAt).toLocaleString()}</small><button onClick={()=>deleteJournal(j.id)} aria-label="Delete journal" className="text-destructive"><Trash2 className="size-4"/></button></div>{j.text&&<p className="mt-2 whitespace-pre-wrap">{j.text}</p>}{j.audioDataUrl&&<audio className="mt-3 w-full" controls src={j.audioDataUrl}/>}<button onClick={()=>speak(j.text||"Your voice journal is saved.")} className="mt-2 text-sm font-bold text-primary">🔊 Read aloud</button></article>):<p className="text-sm text-muted-foreground">No journal entries yet.</p>}</div></Panel></div>}
